### ISSUE TITLE
cn cluster status returning error

### ISSUE THREAD

**Issue by rimolive** [ceph/cn#57]
I can't use `cn cluster status` to check configuration and access keys. The output is:

```
$ cn cluster status ceph
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/ceph/cn/cmd.getAwsKey(0xc4203181f0, 0xe, 0xc42045cdf2, 0x4, 0xc42048819a, 0x4)
	/build/erwan/src/github.com/ceph/cn/cmd/utils.go:357 +0x17a
github.com/ceph/cn/cmd.echoInfo(0xc4203181f0, 0xe)
	/build/erwan/src/github.com/ceph/cn/cmd/utils.go:312 +0x137
github.com/ceph/cn/cmd.statusNano(0xc4200d7440, 0xc4202d3660, 0x1, 0x1)
	/build/erwan/src/github.com/ceph/cn/cmd/status.go:28 +0xb9
github.com/spf13/cobra.(*Command).execute(0xc4200d7440, 0xc4202d3640, 0x1, 0x1, 0xc4200d7440, 0xc4202d3640)
	/build/erwan/src/github.com/spf13/cobra/command.go:704 +0x2c6
github.com/spf13/cobra.(*Command).ExecuteC(0xad5740, 0xc4201aff00, 0x1f, 0x1f)
	/build/erwan/src/github.com/spf13/cobra/command.go:785 +0x2e4
github.com/spf13/cobra.(*Command).Execute(0xad5740, 0x1, 0x5)
	/build/erwan/src/github.com/spf13/cobra/command.go:738 +0x2b
github.com/ceph/cn/cmd.Main(0xc4201aff00, 0x1f)
	/build/erwan/src/github.com/ceph/cn/cmd/main.go:105 +0x53
main.main()
	/build/erwan/src/github.com/ceph/cn/main.go:34 +0xd7

```

**Comment by leseb** [comment]
I've only seen this issue once, only on one machine and I can not reproduce it.
Now, this seems real since you also have the issue.

To be honest, I'm not sure what's going on, I'm looking into this.

**Comment by leseb** [comment]
I only see this issue on Linux, it works fine on OSX.
Still debugging this.

**Comment by leseb** [comment]
@rimolive can you give me your docker version? Thanks

**Comment by rimolive** [comment]
@leseb  I'm using docker 1.13.1, according to ```docker version``` output.

**Comment by leseb** [comment]
Thanks, we are close to solving this bug :), thanks for your patience.
